unless defined?(Motion::Project::Config)
  raise "This file must be required within a RubyMotion project Rakefile."
end

class PhraseConfig
  attr_accessor :auth_token

  def initialize(config)
    @config = config
  end

  def auth_token=(auth_token)
    @auth_token = auth_token
    create_phrase_config_file
  end

private
  def create_phrase_config_file
    return unless @auth_token

    code = <<EOF
# This file is automatically generated. Do not edit.
PHRASE_AUTH_TOKEN = "#{@auth_token}"
PHRASE_API_BASE_URI = "http://localhost:3000/api/v1/"
EOF
    config_file = './app/phrase_config.rb'
    unless File.exist?(config_file)
      File.open(config_file, 'w') { |f| f.write(code) }
    end
    files = @config.files.flatten
    files << config_file unless files.find { |f| File.expand_path(f) == File.expand_path(config_file) }
  end
end

module Motion
  module Project
    class Config
      variable :phrase

      def phrase
        @phrase ||= PhraseConfig.new(self)
      end
    end
  end
end
